# Generated by Django 6.0.3 on 2026-03-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaBotanica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('filas', models.IntegerField(default=10)),
                ('columnas', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('objetivo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=5)),
                ('epoca_siembra', models.CharField(max_length=100)),
                ('epoca_trasplante', models.CharField(blank=True, max_length=100)),
                ('distancia_plantas', models.IntegerField()),
                ('distancia_lineas', models.IntegerField()),
                ('plagas_comunes', models.TextField(blank=True)),
                ('enfermedades_comunes', models.TextField(blank=True)),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_huerto.familiabotanica')),
            ],
        ),
        migrations.CreateModel(
            name='Plantacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_plantacion', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('procedencia', models.CharField(blank=True, max_length=100)),
                ('fecha_cosecha_estimada', models.DateField()),
                ('cosechada', models.BooleanField(default=False)),
                ('fila_inicio', models.IntegerField()),
                ('columna_inicio', models.IntegerField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_huerto.cultivo')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_huerto.parcela')),
            ],
        ),
        migrations.CreateModel(
            name='Semilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedad', models.CharField(max_length=100)),
                ('fecha_caducidad', models.DateField()),
                ('stock_gramos', models.FloatField(default=0)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_huerto.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('plantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_huerto.plantacion')),
            ],
        ),
    ]
