# Generated by Django 6.0.3 on 2026-03-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcela',
            name='columnas',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='filas',
        ),
        migrations.AddField(
            model_name='familiabotanica',
            name='color',
            field=models.CharField(default='#2e7d32', help_text='Color para el plano (ej: #8bc34a)', max_length=7),
        ),
        migrations.AddField(
            model_name='parcela',
            name='tipo_tabla',
            field=models.IntegerField(choices=[(1, 'Tabla 1 (17x12 Rectangular)'), (2, 'Tabla 2 (Trapezoidal 6-12m)'), (3, 'Tabla 3 (Irregular 12-6m)')], default=1),
        ),
    ]
