# Generated by Django 6.0.3 on 2026-03-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0002_remove_parcela_columnas_remove_parcela_filas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacion',
            name='columna_fin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='fila_fin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='cantidad',
            field=models.IntegerField(help_text='Total de plantas en este tramo'),
        ),
    ]
