# Generated by Django 6.0.3 on 2026-03-20 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0003_plantacion_columna_fin_plantacion_fila_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='plantacion',
        ),
        migrations.AddField(
            model_name='tarea',
            name='plantaciones',
            field=models.ManyToManyField(blank=True, related_name='tareas', to='gestion_huerto.plantacion'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='todo_el_huerto',
            field=models.BooleanField(default=False, help_text='Marcar si la tarea se ha realizado en todo el huerto'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('REG', 'Riego'), ('HED', 'Hedrar/Escardar'), ('ABO', 'Abonado'), ('POD', 'Poda/Entutorado'), ('TRAT', 'Tratamiento'), ('COSECHA', 'Cosecha'), ('MANT', 'Mantenimiento General')], max_length=10),
        ),
    ]
