# Generated by Django 6.0.3 on 2026-03-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0004_remove_tarea_plantacion_tarea_plantaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacion',
            name='distancia_personalizada',
            field=models.IntegerField(blank=True, help_text='Opcional: cm entre plantas para esta línea', null=True),
        ),
    ]
