# Generated by Django 6.0.3 on 2026-04-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0005_plantacion_distancia_personalizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='epoca_trasplante',
        ),
        migrations.AddField(
            model_name='cultivo',
            name='abono',
            field=models.TextField(blank=True, help_text='Tipo y frecuencia de fertilización'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='clasificacion_rotacion',
            field=models.CharField(blank=True, help_text='Ej: Leguminosa, Cucurbitácea, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='mantenimiento',
            field=models.TextField(blank=True, help_text='Poda, tutorado, etc.'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='marco_plantacion',
            field=models.CharField(blank=True, help_text='Ej: 40x40 cm', max_length=50),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='meses_recoleccion',
            field=models.CharField(blank=True, help_text='Números de meses separados por comas (1-12)', max_length=50),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='meses_siembra',
            field=models.CharField(blank=True, help_text='Números de meses separados por comas (1-12)', max_length=50),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='meses_trasplante',
            field=models.CharField(blank=True, help_text='Números de meses separados por comas (1-12)', max_length=50),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='profundidad_siembra',
            field=models.CharField(blank=True, help_text='Ej: 2-3 cm', max_length=50),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='requiere_trasplante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='riego',
            field=models.TextField(blank=True, help_text='Frecuencia y método recomendado'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='temp_max_germinacion',
            field=models.IntegerField(blank=True, help_text='Temperatura máxima en °C', null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='temp_min_germinacion',
            field=models.IntegerField(blank=True, help_text='Temperatura mínima en °C', null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='temp_optima_germinacion',
            field=models.IntegerField(blank=True, help_text='Temperatura óptima en °C', null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tiempo_germinacion',
            field=models.IntegerField(blank=True, help_text='Días aproximados', null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='distancia_lineas',
            field=models.IntegerField(default=40, help_text='Distancia en cm'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='distancia_plantas',
            field=models.IntegerField(default=40, help_text='Distancia en cm'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='emoji',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='epoca_siembra',
            field=models.CharField(blank=True, help_text='Ej: Primavera-Verano', max_length=100),
        ),
    ]
