# Generated by Django 6.0.3 on 2026-04-04 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0006_remove_cultivo_epoca_trasplante_cultivo_abono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialRotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('plantaciones', models.IntegerField(help_text='Número de plantas plantadas')),
                ('observaciones', models.TextField(blank=True)),
                ('cultivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_huerto.cultivo')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_rotacion', to='gestion_huerto.parcela')),
            ],
            options={
                'ordering': ['-fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='RecomendacionRotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('SOL', 'Solanáceas (Tomate, Pimiento)'), ('LEG', 'Leguminosas (Judía, Guisante)'), ('CRU', 'Crucíferas (Repollo, Brócoli)'), ('LEA', 'Leafy (Lechuga, Espinaca)'), ('CUC', 'Cucurbitáceas (Calabaza, Pepino)'), ('ALL', 'Allium (Cebolla, Ajo)'), ('UMB', 'Umbelíferas (Zanahoria, Apio)'), ('OTR', 'Otros')], max_length=3, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('cultivos_asociados', models.ManyToManyField(help_text='Cultivos que pertenecen a este grupo', to='gestion_huerto.cultivo')),
                ('debe_evitar', models.ManyToManyField(blank=True, help_text='Qué cultivos deben evitarse', related_name='debe_evitar_seguir', to='gestion_huerto.cultivo')),
                ('puede_seguir_a', models.ManyToManyField(blank=True, help_text='Qué cultivos pueden plantarse después', related_name='puede_seguirle', to='gestion_huerto.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='AsociacionCultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asociacion', models.CharField(choices=[('BUENA', 'Buena Asociación'), ('MALA', 'Mala Asociación'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=10)),
                ('descripcion', models.TextField(blank=True, help_text='Razón de la asociación')),
                ('cultivo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asociaciones_como_asociado', to='gestion_huerto.cultivo')),
                ('cultivo_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asociaciones_como_principal', to='gestion_huerto.cultivo')),
            ],
            options={
                'unique_together': {('cultivo_principal', 'cultivo_asociado')},
            },
        ),
    ]
