# Generated by Django 6.0.3 on 2026-04-04 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0007_historialrotacion_recomendacionrotacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(default=datetime.date.today, help_text='Fecha de la compra')),
                ('concepto', models.CharField(help_text='Descripción del producto/servicio', max_length=200)),
                ('categoria', models.CharField(choices=[('SEMILLAS', '🌱 Semillas'), ('PLANTAS', '🌿 Plantas'), ('FERTILIZANTE', '🥗 Fertilizante'), ('HERRAMIENTAS', '🔧 Herramientas'), ('RIEGO', '💧 Riego'), ('ABONO', '🌾 Abono'), ('PROTECCION', '🛡️ Protección'), ('PEST', '🐛 Pesticidas Naturales'), ('SUELO', '🌍 Suelo/Compost'), ('OTRO', '📦 Otro')], help_text='Categoría del gasto', max_length=20)),
                ('coste', models.DecimalField(decimal_places=2, help_text='Coste en euros', max_digits=10)),
                ('lugar_compra', models.CharField(help_text='Dónde se realizó la compra (tienda, online, etc.)', max_length=200)),
                ('cantidad', models.IntegerField(default=1, help_text='Cantidad de unidades compradas')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la compra')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-fecha'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado_suelo',
            field=models.TextField(blank=True, help_text='Notas sobre el estado del suelo durante esta tarea (humedad, textura, etc.)'),
        ),
    ]
