# Generated by Django 6.0.3 on 2026-04-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0009_variedad_cultivo_variedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacion',
            name='invernadero_semillero',
            field=models.DateField(blank=True, help_text='Fecha de siembra en invernadero o semillero', null=True),
        ),
    ]
