# Generated by Django 6.0.3 on 2026-04-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0010_plantacion_invernadero_semillero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='dias_ciclo',
            field=models.IntegerField(blank=True, help_text='Duración total del ciclo en días (desde plantación a cosecha)', null=True),
        ),
    ]
