# Generated by Django 6.0.3 on 2026-04-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0011_cultivo_dias_ciclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='es_general',
            field=models.BooleanField(default=True, help_text='Marcar si es gasto general del huerto (no específico de plantación)'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='plantaciones',
            field=models.ManyToManyField(blank=True, help_text='Plantaciones a las que se asigna este gasto', related_name='gastos', to='gestion_huerto.plantacion'),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='cantidad_cosechada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad cosechada en kg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='fecha_cosecha_real',
            field=models.DateField(blank=True, help_text='Fecha en que se cosechó realmente', null=True),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='unidad_cosecha',
            field=models.CharField(default='kg', help_text='Unidad de cosecha (kg, unidades, cajas, etc.)', max_length=20),
        ),
    ]
