# Generated by Django 6.0.3 on 2026-04-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0012_gasto_es_general_gasto_plantaciones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tratamientonatural',
            options={'verbose_name': 'Tratamiento Natural', 'verbose_name_plural': 'Tratamientos Naturales'},
        ),
        migrations.AddField(
            model_name='tratamientonatural',
            name='ingrediente_activo',
            field=models.CharField(blank=True, help_text='Ej: Aceite de Neem, Jabón Potásico, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='tratamientonatural',
            name='ml_ingrediente_por_litro',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ml de ingrediente por litro de agua final (dosis por litro)', max_digits=5),
        ),
    ]
