# Generated by Django 6.0.3 on 2026-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0013_alter_tratamientonatural_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variedad',
            name='notas_locales',
            field=models.TextField(blank=True, help_text='Notas sobre el origen local y las características únicas de la variedad'),
        ),
    ]
