# Generated by Django 6.0.3 on 2026-04-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0014_variedad_notas_locales'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='ticket_foto',
            field=models.ImageField(blank=True, help_text='Sube la foto del ticket de compra para vincular precios reales con el gasto.', null=True, upload_to='tickets/'),
        ),
    ]
