# Generated by Django 6.0.3 on 2026-04-05 18:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0015_gasto_ticket_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('SEMB', 'Sembrar'), ('REP', 'Repicar'), ('TRAS', 'Trasplantar'), ('REG', 'Riego'), ('HED', 'Hedrar/Escardar'), ('ABO', 'Abonado'), ('POD', 'Poda/Entutorado'), ('TRAT', 'Tratamiento'), ('COSECHA', 'Cosecha'), ('MANT', 'Mantenimiento General')], max_length=10),
        ),
        migrations.CreateModel(
            name='FotoHuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Sube una foto de tu huerto', upload_to='fotos_huerto/%Y/%m/%d/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_foto', models.DateField(default=datetime.date.today, help_text='Fecha en que se tomó la foto (puede ser diferente a la subida)')),
                ('etiqueta', models.CharField(choices=[('GENERAL', '📸 General'), ('INVERNADERO', '🏠 Invernadero'), ('SEMILLERO', '🌱 Semillero'), ('PLAGA', '🐛 Plaga'), ('ENFERMEDAD', '🦠 Enfermedad'), ('COSECHA', '🥕 Cosecha'), ('DESARROLLO', '📈 Desarrollo'), ('RIEGO', '💧 Riego'), ('MANTENIMIENTO', '🔧 Mantenimiento'), ('HITO', '🏆 Hito')], default='GENERAL', help_text='Tipo de foto para filtrado', max_length=20)),
                ('comentario', models.TextField(blank=True, help_text='Notas sobre lo que ves en la foto (estado de la planta, plagas detectadas, etc.)')),
                ('es_hito', models.BooleanField(default=False, help_text='Marcar si es un hito importante (primera flor, primer fruto, etc.)')),
                ('tipo_hito', models.CharField(blank=True, help_text='Ej: Primera Flor, Primer Fruto, Plaga Detectada', max_length=100)),
                ('plantacion', models.ForeignKey(help_text='Plantación específica a la que pertenece esta foto', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gestion_huerto.plantacion')),
            ],
            options={
                'verbose_name': 'Foto del Huerto',
                'verbose_name_plural': 'Fotos del Huerto',
                'ordering': ['-fecha_foto', '-fecha_subida'],
            },
        ),
    ]
