# Generated by Django 6.0.3 on 2026-04-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0016_alter_tarea_tipo_fotohuerto'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacion',
            name='variedad',
            field=models.ForeignKey(blank=True, help_text='Variedad específica plantada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_huerto.variedad'),
        ),
    ]
