# Generated by Django 6.0.3 on 2026-04-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0017_plantacion_variedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_proxima',
            field=models.DateField(blank=True, help_text='Fecha prevista para la próxima tarea de seguimiento', null=True),
        ),
        migrations.AlterField(
            model_name='fotohuerto',
            name='etiqueta',
            field=models.CharField(choices=[('GENERAL', '📸 General'), ('INVERNADERO', '🏠 Invernadero'), ('PLAGA', '🐛 Plagas/Mariquitas'), ('COSECHA', '🥕 Cosecha'), ('DESARROLLO', '📈 Desarrollo'), ('RIEGO', '💧 Riego'), ('MANTENIMIENTO', '🔧 Mantenimiento'), ('HITO', '🏆 Hito')], default='GENERAL', help_text='Tipo de foto para filtrado', max_length=20),
        ),
    ]
