# Generated by Django 6.0.3 on 2026-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0018_tarea_fecha_proxima_alter_fotohuerto_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='zona',
            field=models.CharField(blank=True, help_text='Zona o sector sin cultivo (ej: T1, T2, T3, Tabla 1, Sector Norte)', max_length=120),
        ),
    ]
