# Generated by Django 6.0.3 on 2026-04-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0019_tarea_zona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultivo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='familia',
            field=models.CharField(choices=[('SOL', 'Solanáceas (Tomate, Pimiento, Patata)'), ('LEG', 'Leguminosas (Haba, Guisante, Alubia)'), ('CRU', 'Crucíferas (Brócoli, Repollo, Coliflor)'), ('CUC', 'Cucurbitáceas (Calabaza, Calabacín, Melón)'), ('ALL', 'Aliáceas (Ajo, Cebolla, Puerro)'), ('HOJ', 'Hoja (Lechuga, Acelga)')], help_text='Selecciona la familia botánica del cultivo', max_length=3),
        ),
    ]
