# Generated by Django 6.0.3 on 2026-04-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0020_alter_cultivo_options_alter_cultivo_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='foto_general',
            field=models.ImageField(blank=True, help_text='Foto general de la parcela para mostrar en el plano', null=True, upload_to='parcelas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='familia',
            field=models.CharField(choices=[('SOL', 'Solanáceas (Tomate, Pimiento, Patata)'), ('LEG', 'Leguminosas (Haba, Guisante, Alubia)'), ('CRU', 'Crucíferas (Brócoli, Repollo, Coliflor)'), ('CUC', 'Cucurbitáceas (Calabaza, Calabacín, Melón)'), ('ALL', 'Aliáceas (Ajo, Cebolla, Puerro)'), ('HOJ', 'Hoja (Lechuga, Acelga)'), ('GRA', 'Gramíneas (Maíz)')], help_text='Selecciona la familia botánica del cultivo', max_length=3),
        ),
    ]
