# Generated by Django 6.0.3 on 2026-04-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0021_parcela_foto_general_alter_cultivo_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacion',
            name='precio_unitario_cosecha',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por kg/unidad en el mercado al momento de la cosecha', max_digits=6, null=True),
        ),
    ]
