# Generated by Django 6.0.3 on 2026-04-21 17:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0022_plantacion_precio_unitario_cosecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cosecha', models.DateField(default=datetime.date.today, help_text='Fecha de la cosecha')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad cosechada', max_digits=8)),
                ('unidad', models.CharField(default='kg', help_text='Unidad de medida', max_length=20)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Precio por unidad en el mercado', max_digits=6, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas sobre la cosecha')),
                ('plantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='gestion_huerto.plantacion')),
            ],
            options={
                'verbose_name': 'Cosecha',
                'verbose_name_plural': 'Cosechas',
                'ordering': ['-fecha_cosecha'],
            },
        ),
    ]
