# Generated by Django 6.0.4 on 2026-04-22 15:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0023_cosecha'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asociacioncultivos',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='asociacioncultivos',
            name='cultivo_asociado',
        ),
        migrations.RemoveField(
            model_name='asociacioncultivos',
            name='cultivo_principal',
        ),
        migrations.DeleteModel(
            name='FamiliaBotanica',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='cultivo',
        ),
        migrations.AlterModelOptions(
            name='cultivo',
            options={'ordering': ['nombre'], 'verbose_name': 'Cultivo', 'verbose_name_plural': 'Cultivos'},
        ),
        migrations.AlterModelOptions(
            name='fotohuerto',
            options={'ordering': ['-fecha'], 'verbose_name': 'Foto del Huerto', 'verbose_name_plural': 'Fotos del Huerto'},
        ),
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='historialrotacion',
            options={'ordering': ['-fecha_rotacion'], 'verbose_name': 'Historial de Rotación', 'verbose_name_plural': 'Historial de Rotaciones'},
        ),
        migrations.AlterModelOptions(
            name='parcela',
            options={'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
        migrations.AlterModelOptions(
            name='plantacion',
            options={'ordering': ['-fecha_siembra'], 'verbose_name': 'Plantación', 'verbose_name_plural': 'Plantaciones'},
        ),
        migrations.AlterModelOptions(
            name='recomendacionrotacion',
            options={'verbose_name': 'Recomendación de Rotación', 'verbose_name_plural': 'Recomendaciones de Rotación'},
        ),
        migrations.AlterModelOptions(
            name='tratamientonatural',
            options={'ordering': ['-fecha_aplicacion'], 'verbose_name': 'Tratamiento Natural', 'verbose_name_plural': 'Tratamientos Naturales'},
        ),
        migrations.AlterModelOptions(
            name='variedad',
            options={'verbose_name': 'Variedad', 'verbose_name_plural': 'Variedades'},
        ),
        migrations.RenameField(
            model_name='cultivo',
            old_name='enfermedades_comunes',
            new_name='notas_locales',
        ),
        migrations.RenameField(
            model_name='fotohuerto',
            old_name='fecha_subida',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='historialrotacion',
            old_name='fecha_fin',
            new_name='fecha_rotacion',
        ),
        migrations.RenameField(
            model_name='plantacion',
            old_name='cosechada',
            new_name='invernadero',
        ),
        migrations.RenameField(
            model_name='tratamientonatural',
            old_name='ingredientes',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='clasificacion_rotacion',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='distancia_lineas',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='distancia_plantas',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='mantenimiento',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='marco_plantacion',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='meses_recoleccion',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='meses_siembra',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='meses_trasplante',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='plagas_comunes',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='profundidad_siembra',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='requiere_trasplante',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='riego',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='temp_max_germinacion',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='temp_min_germinacion',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='temp_optima_germinacion',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='tiempo_germinacion',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='variedad',
        ),
        migrations.RemoveField(
            model_name='fotohuerto',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='fotohuerto',
            name='es_hito',
        ),
        migrations.RemoveField(
            model_name='fotohuerto',
            name='fecha_foto',
        ),
        migrations.RemoveField(
            model_name='fotohuerto',
            name='tipo_hito',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='coste',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='lugar_compra',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='historialrotacion',
            name='cultivo',
        ),
        migrations.RemoveField(
            model_name='historialrotacion',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='historialrotacion',
            name='plantaciones',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='tipo_tabla',
        ),
        migrations.RemoveField(
            model_name='plantacion',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='plantacion',
            name='cantidad_cosechada',
        ),
        migrations.RemoveField(
            model_name='plantacion',
            name='fecha_cosecha_estimada',
        ),
        migrations.RemoveField(
            model_name='plantacion',
            name='fecha_cosecha_real',
        ),
        migrations.RemoveField(
            model_name='plantacion',
            name='fecha_plantacion',
        ),
        migrations.RemoveField(
            model_name='plantacion',
            name='invernadero_semillero',
        ),
        migrations.RemoveField(
            model_name='plantacion',
            name='procedencia',
        ),
        migrations.RemoveField(
            model_name='plantacion',
            name='unidad_cosecha',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='plantaciones',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='todo_el_huerto',
        ),
        migrations.RemoveField(
            model_name='tratamientonatural',
            name='ingrediente_activo',
        ),
        migrations.RemoveField(
            model_name='tratamientonatural',
            name='ml_ingrediente_por_litro',
        ),
        migrations.RemoveField(
            model_name='tratamientonatural',
            name='objetivo',
        ),
        migrations.AddField(
            model_name='cultivo',
            name='epoca_recoleccion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='epoca_trasplante',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fotohuerto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=200),
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gasto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='gasto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='historialrotacion',
            name='cultivo_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotaciones_anteriores', to='gestion_huerto.cultivo'),
        ),
        migrations.AddField(
            model_name='historialrotacion',
            name='cultivo_siguiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotaciones_siguientes', to='gestion_huerto.cultivo'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='columnas',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='parcela',
            name='filas',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='fecha_recoleccion_esperada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='fecha_siembra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='fecha_trasplante',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='semillero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recomendacionrotacion',
            name='cultivo_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_actual', to='gestion_huerto.cultivo'),
        ),
        migrations.AddField(
            model_name='recomendacionrotacion',
            name='cultivo_recomendado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_siguiente', to='gestion_huerto.cultivo'),
        ),
        migrations.AddField(
            model_name='recomendacionrotacion',
            name='razon',
            field=models.TextField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='recomendacionrotacion',
            unique_together={('cultivo_actual', 'cultivo_recomendado')},
        ),
        migrations.AddField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tarea',
            name='plantacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='gestion_huerto.plantacion'),
        ),
        migrations.AddField(
            model_name='tratamientonatural',
            name='fecha_aplicacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tratamientonatural',
            name='plantacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='gestion_huerto.plantacion'),
        ),
        migrations.AddField(
            model_name='tratamientonatural',
            name='tipo',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('curativo', 'Curativo'), ('fertilizante', 'Fertilizante'), ('otros', 'Otros')], default='preventivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='fecha_cosecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='unidad',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('u', 'Unidades'), ('cajas', 'Cajas'), ('otros', 'Otros')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='abono',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='dias_ciclo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='epoca_siembra',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='familia',
            field=models.CharField(choices=[('hortalizas', 'Hortalizas'), ('frutas', 'Frutas'), ('legumbres', 'Legumbres'), ('cereales', 'Cereales'), ('hierbas', 'Hierbas aromáticas'), ('otros', 'Otros')], default='hortalizas', max_length=20),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fotohuerto',
            name='etiqueta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fotohuerto',
            name='imagen',
            field=models.ImageField(upload_to='fotos_huerto/'),
        ),
        migrations.AlterField(
            model_name='fotohuerto',
            name='plantacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gestion_huerto.plantacion'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='es_general',
            field=models.BooleanField(default=False, help_text='Si es True, no está asociado a plantaciones específicas'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='plantaciones',
            field=models.ManyToManyField(blank=True, related_name='gastos', to='gestion_huerto.plantacion'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='ticket_foto',
            field=models.ImageField(blank=True, null=True, upload_to='gastos/'),
        ),
        migrations.AlterField(
            model_name='historialrotacion',
            name='parcela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_rotaciones', to='gestion_huerto.parcela'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='foto_general',
            field=models.ImageField(blank=True, null=True, upload_to='parcelas/'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='columna_fin',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='columna_inicio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantaciones', to='gestion_huerto.cultivo'),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='distancia_personalizada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia en cm entre plantas', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='fila_fin',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='fila_inicio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='parcela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantaciones', to='gestion_huerto.parcela'),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='precio_unitario_cosecha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='variedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantaciones', to='gestion_huerto.variedad'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado_suelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_proxima',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('siembra', 'Siembra'), ('trasplante', 'Trasplante'), ('riego', 'Riego'), ('abono', 'Abono'), ('tratamiento', 'Tratamiento'), ('cosecha', 'Cosecha'), ('labores', 'Labores culturales'), ('foto', 'Foto'), ('otros', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='zona',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='variedad',
            name='notas_locales',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='variedad',
            unique_together={('nombre', 'cultivo')},
        ),
        migrations.DeleteModel(
            name='AsociacionCultivos',
        ),
        migrations.DeleteModel(
            name='Semilla',
        ),
        migrations.RemoveField(
            model_name='recomendacionrotacion',
            name='cultivos_asociados',
        ),
        migrations.RemoveField(
            model_name='recomendacionrotacion',
            name='debe_evitar',
        ),
        migrations.RemoveField(
            model_name='recomendacionrotacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='recomendacionrotacion',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='recomendacionrotacion',
            name='puede_seguir_a',
        ),
    ]
