# Generated by Django 6.0.4 on 2026-04-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0024_alter_asociacioncultivos_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='clasificacion_rotacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='distancia_lineas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='distancia_plantas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='emoji',
            field=models.CharField(blank=True, default='🌱', max_length=10),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='enfermedades_comunes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='mantenimiento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='marco_plantacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='meses_recoleccion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='meses_siembra',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='meses_trasplante',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='plagas_comunes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='profundidad_siembra',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='requiere_trasplante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='riego',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='temp_max_germinacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='temp_min_germinacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='temp_optima_germinacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tiempo_germinacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
