# Generated by Django 6.0.3 on 2026-04-24 11:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0025_cultivo_clasificacion_rotacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotohuerto',
            options={'ordering': ['-fecha_foto', '-fecha_subida'], 'verbose_name': 'Foto del Huerto', 'verbose_name_plural': 'Fotos del Huerto'},
        ),
        migrations.RenameField(
            model_name='fotohuerto',
            old_name='fecha',
            new_name='fecha_subida',
        ),
        migrations.RemoveField(
            model_name='fotohuerto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='fotohuerto',
            name='comentario',
            field=models.TextField(blank=True, help_text='Notas sobre lo que ves en la foto (estado de la planta, plagas detectadas, etc.)'),
        ),
        migrations.AddField(
            model_name='fotohuerto',
            name='es_hito',
            field=models.BooleanField(default=False, help_text='Marcar si es un hito importante (primera flor, primer fruto, etc.)'),
        ),
        migrations.AddField(
            model_name='fotohuerto',
            name='fecha_foto',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Fecha en que se tomó la foto (puede ser diferente a la subida)'),
        ),
        migrations.AddField(
            model_name='fotohuerto',
            name='tipo_hito',
            field=models.CharField(blank=True, help_text='Ej: Primera Flor, Primer Fruto, Plaga Detectada', max_length=100),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='familia',
            field=models.CharField(choices=[('solanaceas', 'Solanáceas (Tomate, Pimiento, Patata)'), ('leguminosas', 'Leguminosas (Haba, Guisante, Alubia)'), ('cruciferas', 'Crucíferas (Brócoli, Repollo, Coliflor)'), ('cucurbitaceas', 'Cucurbitáceas (Calabaza, Calabacín, Melón)'), ('aliaceas', 'Alíaceas (Ajo, Cebolla, Puerro)'), ('hoja', 'Hoja (Lechuga, Acelga)'), ('gramineas', 'Gramíneas (Maíz)'), ('otros', 'Otros')], default='hortalizas', max_length=20),
        ),
        migrations.AlterField(
            model_name='fotohuerto',
            name='etiqueta',
            field=models.CharField(choices=[('GENERAL', '📸 General'), ('INVERNADERO', '🏠 Invernadero'), ('SEMILLERO', '🌱 Semillero'), ('PLAGA', '🐛 Plaga'), ('ENFERMEDAD', '🦠 Enfermedad'), ('COSECHA', '🥕 Cosecha'), ('DESARROLLO', '📈 Desarrollo'), ('RIEGO', '💧 Riego'), ('MANTENIMIENTO', '🔧 Mantenimiento'), ('HITO', '🏆 Hito')], default='GENERAL', help_text='Tipo de foto para filtrado', max_length=20),
        ),
        migrations.AlterField(
            model_name='fotohuerto',
            name='imagen',
            field=models.ImageField(help_text='Sube una foto de tu huerto', upload_to='fotos_huerto/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='fotohuerto',
            name='plantacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gestion_huerto.plantacion'),
        ),
    ]
