# Generated by Django 6.0.3 on 2026-04-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0026_alter_fotohuerto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacion',
            name='procedencia',
            field=models.CharField(blank=True, help_text='Origen de la planta o semilla', max_length=200),
        ),
    ]
