# Generated by Django 6.0.4 on 2026-04-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0027_plantacion_procedencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='tipo_tabla',
            field=models.PositiveIntegerField(default=1, help_text='Tipo de tabla para validación geométrica (1=rectangular, 2=triangular, 3=diagonal)'),
        ),
    ]
