# Generated by Django 6.0.3 on 2026-04-26 10:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0028_parcela_tipo_tabla'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacion',
            name='fecha_germinado_estimado',
            field=models.DateField(blank=True, help_text='Fecha prevista para la germinación', null=True),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='fecha_germinado_real',
            field=models.DateField(blank=True, help_text='Fecha en que germinó', null=True),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='fecha_recoleccion_inicio',
            field=models.DateField(blank=True, help_text='Fecha prevista para inicio de cosecha', null=True),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='fecha_siembra_estimada',
            field=models.DateField(blank=True, help_text='Fecha prevista para la siembra', null=True),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='fecha_siembra_real',
            field=models.DateField(blank=True, help_text='Fecha en que se sembró', null=True),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='fecha_recoleccion_esperada',
            field=models.DateField(blank=True, help_text='Deprecated: usar fecha_recoleccion_inicio', null=True),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='fecha_siembra',
            field=models.DateField(blank=True, help_text='Deprecated: usar fecha_siembra_real', null=True),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='fecha_trasplante',
            field=models.DateField(blank=True, help_text='Fecha de trasplante (si aplica)', null=True),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='procedencia',
            field=models.CharField(choices=[('semilla_propia', 'Semilla Propia'), ('compra_local', 'Compra Local'), ('otro', 'Otro')], default='otro', help_text='Origen de la planta o semilla', max_length=20),
        ),
        migrations.CreateModel(
            name='FotoPlantacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Foto del estado de la plantación', upload_to='fotos_plantacion/%Y/%m/%d/')),
                ('fecha_foto', models.DateField(default=django.utils.timezone.localdate, help_text='Fecha en que se tomó la foto')),
                ('tipo_foto', models.CharField(choices=[('germinacion', 'Germinación'), ('primer_brote', 'Primer brote'), ('desarrollo', 'Desarrollo'), ('floración', 'Floración'), ('cuajado', 'Cuajado'), ('maduración', 'Maduración'), ('cosecha', 'Cosecha'), ('plagas', 'Plagas/Enfermedades'), ('hito', 'Hito importante'), ('otro', 'Otro')], default='desarrollo', help_text='Etapa de desarrollo cuando se tomó la foto', max_length=20)),
                ('dias_ciclo', models.PositiveIntegerField(blank=True, help_text='Días desde la siembra cuando se tomó la foto', null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Notas sobre el estado observado, cambios, plagas detectadas, etc.')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('plantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_plantacion', to='gestion_huerto.plantacion')),
            ],
            options={
                'verbose_name': 'Foto de Plantación',
                'verbose_name_plural': 'Fotos de Plantaciones',
                'ordering': ['-fecha_foto', '-fecha_subida'],
            },
        ),
    ]
