# Generated by Django 6.0.4 on 2026-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0029_plantacion_fecha_germinado_estimado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantacion',
            name='invernadero',
        ),
        migrations.RemoveField(
            model_name='plantacion',
            name='semillero',
        ),
        migrations.AddField(
            model_name='plantacion',
            name='tipo_siembra',
            field=models.CharField(choices=[('terreno', 'Siembra en terreno'), ('semillero', 'Siembra en semillero')], default='terreno', help_text='¿Dónde se siembra? (terreno directamente o semillero para trasplantar)', max_length=20),
        ),
    ]
