# Generated by Django 6.0.3 on 2026-04-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0030_remove_plantacion_invernadero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacion',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, help_text='Número de plantas plantadas', null=True),
        ),
    ]
