# Generated by Django 6.0.3 on 2026-04-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0031_plantacion_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='columnas',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='filas',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='tipo_tabla',
            field=models.PositiveIntegerField(choices=[(1, 'Tabla 1 (17x12 Rectangular)'), (2, 'Tabla 2 (Trapezoidal 6-12m)'), (3, 'Tabla 3 (Irregular 12-6m)')], default=1, help_text='Tipo de tabla para validación geométrica (1=rectangular, 2=triangular, 3=diagonal)'),
        ),
    ]
