# Generated by Django 6.0.3 on 2026-04-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0032_alter_parcela_columnas_alter_parcela_filas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='plantaciones',
            field=models.ManyToManyField(blank=True, related_name='tareas_m2m', to='gestion_huerto.plantacion'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='todo_el_huerto',
            field=models.BooleanField(default=False),
        ),
    ]
