# Generated by Django 6.0.3 on 2026-04-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0033_tarea_plantaciones_tarea_todo_el_huerto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='grupo_rotacion',
            field=models.CharField(blank=True, choices=[('fruto', 'Grupo A — Fruto (Solanáceas, Cucurbitáceas)'), ('hoja_raiz', 'Grupo B — Hoja/Raíz (Crucíferas, Lechugas, Zanahorias)'), ('leguminosa', 'Grupo C — Leguminosa (Fija nitrógeno)'), ('bulbo', 'Grupo D — Bulbo/Limpieza (Aliáceas)')], help_text='Grupo de rotación al que pertenece el cultivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='familia',
            field=models.CharField(choices=[('solanaceas', 'Solanáceas (Tomate, Pimiento, Berenjena, Patata)'), ('cucurbitaceas', 'Cucurbitáceas (Calabaza, Calabacín, Pepino, Melón)'), ('cruciferas', 'Crucíferas (Brócoli, Repollo, Coliflor, Rábano)'), ('hoja', 'Hoja (Lechuga, Espinaca, Acelga)'), ('umbeliferas', 'Umbelíferas (Zanahoria, Apio, Perejil, Hinojo)'), ('leguminosas', 'Leguminosas (Haba, Guisante, Judía, Alubia)'), ('aliaceas', 'Alíaceas (Ajo, Cebolla, Puerro, Cebolleta)'), ('gramineas', 'Gramíneas (Maíz, Trigo)'), ('compuestas', 'Compuestas (Alcachofa, Girasol)'), ('otros', 'Otros')], default='hortalizas', max_length=20),
        ),
    ]
