# Generated by Django 6.0.3 on 2026-04-28 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0034_cultivo_grupo_rotacion_alter_cultivo_familia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantacion',
            name='fecha_siembra_estimada',
        ),
        migrations.RemoveField(
            model_name='plantacion',
            name='fecha_siembra_real',
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='familia',
            field=models.CharField(choices=[('solanaceas', 'Solanáceas (Tomate, Pimiento, Berenjena, Patata)'), ('cucurbitaceas', 'Cucurbitáceas (Calabaza, Calabacín, Pepino, Melón)'), ('cruciferas', 'Crucíferas (Brócoli, Repollo, Coliflor, Rábano)'), ('hoja', 'Hoja (Lechuga, Espinaca, Acelga)'), ('umbeliferas', 'Umbelíferas (Zanahoria, Apio, Perejil, Hinojo)'), ('leguminosas', 'Leguminosas (Haba, Guisante, Judía, Alubia)'), ('aliaceas', 'Alíaceas (Ajo, Cebolla, Puerro, Cebolleta)'), ('gramineas', 'Gramíneas (Maíz, Trigo)'), ('compuestas', 'Compuestas (Alcachofa, Girasol)'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
        migrations.CreateModel(
            name='RotacionParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('temporada', models.CharField(blank=True, help_text='Ej: Primavera 2026', max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotaciones', to='gestion_huerto.cultivo')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotaciones', to='gestion_huerto.parcela')),
            ],
            options={
                'verbose_name': 'Rotación de parcela',
                'verbose_name_plural': 'Rotaciones de parcelas',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
