# Generated by Django 6.0.3 on 2026-04-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0035_remove_plantacion_fecha_siembra_estimada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('preparar', 'Preparar terreno'), ('siembra', 'Siembra'), ('trasplante', 'Trasplante'), ('riego', 'Riego'), ('abono', 'Abono'), ('tratamiento', 'Tratamiento'), ('hedrar', 'Hedrado o deshierbe'), ('cosecha', 'Cosecha'), ('labores', 'Labores de supervisión'), ('foto', 'Foto'), ('otros', 'Otros')], max_length=20),
        ),
    ]
