# Generated by Django 6.0.3 on 2026-04-30 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0036_alter_tarea_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='es_perenne',
            field=models.BooleanField(default=False, help_text='Marca si la planta permanece varios años (ej. frutales, aromáticas perennes)'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipo_cultivo',
            field=models.CharField(choices=[('hortaliza', 'Hortaliza'), ('frutal', 'Frutal'), ('flor', 'Flor')], default='hortaliza', help_text='Hortaliza, frutal o flor', max_length=20),
        ),
        migrations.CreateModel(
            name='FichaFlor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion_ecologica', models.CharField(choices=[('polinizadores', 'Atracción de polinizadores'), ('control_plagas', 'Apoyo al control de plagas'), ('biodiversidad', 'Biodiversidad y refugio'), ('ornamental', 'Ornamental'), ('comestible', 'Flor comestible')], default='biodiversidad', help_text='Función principal de esta flor en el huerto', max_length=30)),
                ('floracion_inicio_mes', models.PositiveSmallIntegerField(blank=True, help_text='Mes aproximado de inicio de floración (1-12)', null=True)),
                ('floracion_fin_mes', models.PositiveSmallIntegerField(blank=True, help_text='Mes aproximado de fin de floración (1-12)', null=True)),
                ('atrae_polinizadores', models.BooleanField(default=True, help_text='Marca si atrae abejas y otros polinizadores')),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre asociaciones, resiembras espontáneas, etc.')),
                ('cultivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_flor', to='gestion_huerto.cultivo')),
            ],
            options={
                'verbose_name': 'Ficha de flor',
                'verbose_name_plural': 'Fichas de flores',
            },
        ),
        migrations.CreateModel(
            name='FichaFrutal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedad_frutal', models.CharField(blank=True, help_text='Ej: Golden, Starking, etc.', max_length=100)),
                ('portainjerto', models.CharField(blank=True, help_text='Si lo conoces, anótalo', max_length=100)),
                ('tipo_polinizacion', models.CharField(choices=[('autofertil', 'Autofértil'), ('cruzada', 'Polinización cruzada'), ('desconocida', 'Desconocida')], default='desconocida', max_length=20)),
                ('necesita_polinizador', models.BooleanField(default=False, help_text='Marca si necesita otro árbol compatible cerca')),
                ('marco_plantacion_m', models.DecimalField(blank=True, decimal_places=2, help_text='Marco en metros, ej: 4.00', max_digits=5, null=True)),
                ('tipo_poda', models.CharField(choices=[('formacion', 'Formación'), ('mantenimiento', 'Mantenimiento'), ('fructificacion', 'Fructificación'), ('renovacion', 'Renovación'), ('sin_definir', 'Sin definir')], default='sin_definir', max_length=20)),
                ('fecha_ultima_poda', models.DateField(blank=True, help_text='Última poda realizada', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre vigor, producción, problemas, etc.')),
                ('cultivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_frutal', to='gestion_huerto.cultivo')),
            ],
            options={
                'verbose_name': 'Ficha de frutal',
                'verbose_name_plural': 'Fichas de frutales',
            },
        ),
    ]
