# Generated by Django 6.0.3 on 2026-04-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0037_cultivo_es_perenne_cultivo_tipo_cultivo_fichaflor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacion',
            name='estado',
            field=models.CharField(choices=[('planificada', 'Planificada'), ('sembrada', 'Sembrada'), ('germinada', 'Germinada'), ('trasplantada', 'Trasplantada'), ('en_cultivo', 'En cultivo'), ('en_cosecha', 'En cosecha'), ('finalizada', 'Finalizada'), ('perdida', 'Perdida')], default='sembrada', help_text='Estado actual de la plantación', max_length=20),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='observaciones_seguimiento',
            field=models.TextField(blank=True, help_text='Resumen general del seguimiento del cultivo'),
        ),
        migrations.AddField(
            model_name='plantacion',
            name='origen_plantel',
            field=models.CharField(blank=True, help_text='Ej: semillero propio, vivero local, intercambio, etc.', max_length=100),
        ),
    ]
