# Generated by Django 6.0.3 on 2026-05-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0038_plantacion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tiempo_estimado_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tiempo_real_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('preparar', 'Preparar terreno'), ('siembra', 'Siembra'), ('repicado', 'Repicado'), ('trasplante', 'Trasplante'), ('riego', 'Riego'), ('abono', 'Abono'), ('tratamiento', 'Tratamiento'), ('hedrar', 'Hedrado o deshierbe'), ('cosecha', 'Cosecha'), ('labores', 'Labores de supervisión'), ('foto', 'Foto'), ('otros', 'Otros')], max_length=20),
        ),
    ]
