# Generated by Django 6.0.3 on 2026-05-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0039_tarea_tiempo_estimado_min_tarea_tiempo_real_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacion',
            name='modo_implantacion',
            field=models.CharField(blank=True, choices=[('directa', 'Siembra directa en terreno'), ('semillero', 'Semillero + trasplante'), ('plantel', 'Plantel comprado')], help_text='Cómo entró este cultivo al terreno: siembra directa, desde semillero o plantel comprado', max_length=20, null=True),
        ),
    ]
