# Generated by Django 6.0.3 on 2026-05-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0040_plantacion_modo_implantacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantacion',
            name='modo_implantacion',
            field=models.CharField(choices=[('directa', 'Siembra directa'), ('semillero', 'Desde semillero'), ('plantel', 'Plantel comprado')], default='directa', help_text='Cómo entra el cultivo al terreno definitivo.', max_length=20, verbose_name='Modo de implantación'),
        ),
        migrations.AlterField(
            model_name='plantacion',
            name='procedencia',
            field=models.CharField(choices=[('semilla_propia', 'Semilla Propia'), ('compra_local', 'Compra Local'), ('ajero corella', 'Ajero Corella'), ('piensos muga', 'Piensos Muga'), ('cintruenigo', 'Cintruenigo'), ('otro', 'Otro')], default='otro', help_text='Origen de la planta o semilla', max_length=20),
        ),
    ]
