# Generated by Django 6.0.3 on 2026-05-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0041_alter_plantacion_modo_implantacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemedioBotica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('insecticida', 'Insecticida'), ('fungicida', 'Fungicida'), ('bioestimulante', 'Bioestimulante'), ('fertilizante', 'Fertilizante'), ('repelente', 'Repelente'), ('cicatrizante', 'Cicatrizante'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('objetivo', models.CharField(help_text='Ej: pulgón, oídio, mildiu, vigor, prevención...', max_length=200)),
                ('ingredientes', models.TextField()),
                ('preparacion', models.TextField()),
                ('dosis', models.CharField(blank=True, help_text='Ej: 10 ml/L, 100 g por 5 L, diluir al 20%...', max_length=200)),
                ('modo_aplicacion', models.CharField(choices=[('foliar', 'Aplicación foliar'), ('suelo', 'Aplicación al suelo'), ('riego', 'En agua de riego'), ('pincelado', 'Pincelado localizado'), ('trampa', 'Trampa o cebo'), ('otro', 'Otro')], default='foliar', max_length=20)),
                ('periodicidad', models.CharField(blank=True, help_text='Ej: cada 7 días, tras lluvias, solo preventivo...', max_length=200)),
                ('momento_ideal', models.CharField(blank=True, help_text='Ej: al atardecer, sin viento, evitar horas de sol fuerte.', max_length=200)),
                ('advertencias', models.TextField(blank=True, help_text='Precauciones, incompatibilidades, riesgo de fitotoxicidad...')),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Remedio de botica',
                'verbose_name_plural': 'Remedios de botica',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='TratamientoNatural',
        ),
    ]
