# Generated by Django 6.0.3 on 2026-05-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0042_remediobotica_delete_tratamientonatural'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionRemedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('problema_detectado', models.CharField(help_text='Ej: pulgón, mildiu, prevención, debilitamiento...', max_length=200)),
                ('dosis_aplicada', models.CharField(blank=True, help_text='Ej: 12 ml/L, pulverización fina al atardecer', max_length=200)),
                ('condiciones', models.CharField(blank=True, help_text='Ej: tarde húmeda, tras lluvia, calor suave...', max_length=200)),
                ('resultado', models.CharField(blank=True, choices=[('muy_bueno', 'Muy bueno'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('bajo', 'Bajo'), ('sin_cambios', 'Sin cambios')], max_length=20)),
                ('repetir', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_remedios', to='gestion_huerto.cultivo')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_remedios', to='gestion_huerto.parcela')),
                ('remedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='gestion_huerto.remediobotica')),
                ('tarea_seguimiento', models.ForeignKey(blank=True, help_text='Tarea generada automáticamente para revisar el efecto de esta aplicación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_botica', to='gestion_huerto.tarea')),
            ],
            options={
                'verbose_name': 'Aplicación de remedio',
                'verbose_name_plural': 'Aplicaciones de remedios',
                'ordering': ['-fecha_aplicacion', '-id'],
            },
        ),
    ]
