# Generated by Django 6.0.3 on 2026-05-02 15:38

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0043_aplicacionremedio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha_compra'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='total',
        ),
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('semillas', 'Semillas y Plantones'), ('abonos', 'Abonos y Compost'), ('herramientas', 'Herramientas'), ('riego', 'Sistema de Riego'), ('tratamientos', 'Tratamientos Ecológicos'), ('sustratos', 'Sustratos y Tierra'), ('infraestructura', 'Infraestructura'), ('otros', 'Otros')], default='otros', help_text='Categoría del gasto', max_length=20),
        ),
        migrations.AddField(
            model_name='gasto',
            name='concepto',
            field=models.CharField(default='Sin concepto', help_text='Descripción del producto o servicio', max_length=200),
        ),
        migrations.AddField(
            model_name='gasto',
            name='coste',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='Precio unitario en euros', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Fecha en que se realizó la compra'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='lugar_compra',
            field=models.CharField(default='No indicado', help_text='Tienda o proveedor', max_length=100),
        ),
        migrations.AddField(
            model_name='gasto',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones adicionales'),
        ),
        migrations.AlterField(
            model_name='fotoplantacion',
            name='tipo_foto',
            field=models.CharField(choices=[('germinacion', 'Germinación'), ('primer_brote', 'Primer brote'), ('desarrollo', 'Desarrollo'), ('floracion', 'Floración'), ('cuajado', 'Cuajado'), ('maduracion', 'Maduración'), ('cosecha', 'Cosecha'), ('plagas', 'Plagas/Enfermedades'), ('hito', 'Hito importante'), ('otro', 'Otro')], default='desarrollo', help_text='Etapa de desarrollo cuando se tomó la foto', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Número de unidades compradas'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='ticket_foto',
            field=models.ImageField(blank=True, help_text='Foto del ticket de compra', null=True, upload_to='tickets_gastos/%Y/%m/'),
        ),
    ]
