# Generated by Django 6.0.3 on 2026-05-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0044_alter_gasto_options_remove_gasto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoplantacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plantacion',
            options={},
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('abono', 'Abono'), ('compostaje', 'Compostaje'), ('cosecha', 'Cosecha'), ('control_plagas', 'Control de plagas'), ('entutorado', 'Entutorado'), ('foto', 'Foto'), ('hedrar', 'Hedrado o deshierbe'), ('labores', 'Labores de supervisión'), ('otros', 'Otros'), ('preparar', 'Preparar terreno'), ('repicado', 'Repicado'), ('riego', 'Riego'), ('siembra', 'Siembra'), ('trasplante', 'Trasplante'), ('tratamiento', 'Tratamiento')], max_length=20),
        ),
    ]
