# Generated by Django 6.0.3 on 2026-05-24 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0045_alter_fotoplantacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosecha',
            options={'ordering': ['-fecha_cosecha', '-id'], 'verbose_name': 'Cosecha', 'verbose_name_plural': 'Cosechas'},
        ),
        migrations.AlterModelOptions(
            name='plantacion',
            options={'ordering': ['-fecha_siembra'], 'verbose_name': 'Plantación', 'verbose_name_plural': 'Plantaciones'},
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='fecha_cosecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de mercado por unidad', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('abono', 'Abono'), ('compostaje', 'Compostaje'), ('cosecha', 'Cosecha'), ('control_plagas', 'Control de plagas'), ('entutorado', 'Entutorado'), ('foto', 'Foto'), ('gallinero', 'Gallinero'), ('hedrar', 'Hedrado o deshierbe'), ('labores', 'Labores de supervisión'), ('otros', 'Otros'), ('preparar', 'Preparar terreno'), ('repicado', 'Repicado'), ('riego', 'Riego'), ('siembra', 'Siembra'), ('trasplante', 'Trasplante'), ('tratamiento', 'Tratamiento')], max_length=20),
        ),
    ]
