# Generated by Django 6.0.3 on 2026-05-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerto', '0046_alter_cosecha_options_alter_plantacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('abono', 'Abono'), ('aporcar', 'Aporcado o escarda'), ('compostaje', 'Compostaje'), ('cosecha', 'Cosecha'), ('control_plagas', 'Control de plagas'), ('entutorado', 'Entutorado'), ('foto', 'Foto'), ('gallinero', 'Gallinero'), ('hedrar', 'Hedrado o deshierbe'), ('labores', 'Labores de supervisión'), ('otros', 'Otros'), ('preparar', 'Preparar terreno'), ('repicado', 'Repicado'), ('riego', 'Riego'), ('siembra', 'Siembra'), ('trasplante', 'Trasplante'), ('tratamiento', 'Tratamiento')], max_length=20),
        ),
    ]
